# Generated by Django 4.0.6 on 2022-07-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_directors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directors',
            new_name='Director',
        ),
    ]
