# Generated by Django 4.0.6 on 2022-07-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_actor_director_country_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(null=True, to='viewer.actor'),
        ),
    ]
